coverage:
  round: nearest
  ignore:
    - /utils/byteinterval_linkedlist.go
    - /utils/packetinterval_linkedlist.go
    - /ackhandlerlegacy/packet_linkedlist.go

notify:
  status:
    project:
      default:
        target: 0
    patch:
      default:
        target: 0
